### ISSUE TITLE
Update messed things up

### ISSUE THREAD

**Issue by JonWel** [JunoLab/uber-juno#12]
I was using Atom with uber-juno to use it as a Julia IDE, but thigs got messed up after I updated Atom and some of Julia related Atom's package.
Now, Atom get stuck with a
```
ERROR: could not open file C:\Users\my 
```
Where it looks it wants to access my user directory "my name".

How can I clean everything (all the settings) so I can reinstall it fresh (with the latest version)?
I tried to install Atom and Julia and remove config files, but it did not change to the problem and it looked like it still had some settings hidden somewhere else.

So right now I cannot execute any code from Atom.

Thanks for any help.

**Comment by MikeInnes** [comment]
This should be fixed if you update again; let us know how that goes.

**Comment by JonWel** [comment]
Thanks @MikeInnes, that fixed it!

Updated to julia-client 0.5.1.
Closed Atom.
Run `Pkg.update()` in Julia (it updated Mustache).
Started Atom again
Started Julia:
```Julia
INFO: Recompiling stale cache file C:\Users\My Name\.julia\lib\v0.4\HttpParser.ji for module HttpParser.
ERROR: LoadError: LoadError: Unable to load 

lib (C:\Users\My Name\.julia\v0.4\HttpParser\deps\usr\lib\libhttp_parser64.DLL)

Please re-run Pkg.build(package), and restart Julia.
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at client.jl:257
 in _start at client.jl:378
while loading C:\Users\My Name\.julia\v0.4\HttpParser\src\..\deps\deps.jl, in expression starting on line 13
while loading C:\Users\My Name\.julia\v0.4\HttpParser\src\HttpParser.jl, in expression starting on line 9
ERROR: LoadError: Failed to precompile HttpParser to C:\Users\My Name\.julia\lib\v0.4\HttpParser.ji
 in compilecache at loading.jl:400
 in recompile_stale at loading.jl:476
 in _require_from_serialized at loading.jl:83
 in stale_cachefile at loading.jl:457
 in recompile_stale at loading.jl:474
 in _require_from_serialized at loading.jl:83
 in stale_cachefile at loading.jl:457
 in recompile_stale at loading.jl:474
 in _require_from_serialized at loading.jl:83
 in stale_cachefile at loading.jl:457
 in recompile_stale at loading.jl:474
 in _require_from_serialized at loading.jl:83
while loading C:\Users\My Name\.atom\packages\julia-client\script\boot.jl, in expression starting on line 35
```
And suggested to:
```
Go to the Packages → Julia → Open Terminal menu and
run `Pkg.update()`in Julia, then try again.
If you still see an issue, please report it to:
    http://discuss.junolab.org/
```
So I did run the `Pkg.update()` again, but it did not seems to do anything to `HttpParser`, so I ran `Pkg.build("HttpParser")` as suggested in Julia's message, which seemed to do something.
Than I restarted Atom ans start Julia.
This recompiled several packages (HttpServer, Mux, WebSockets, Blink, Mustache).
And it now works :)
