### ISSUE TITLE
precompilation error in Atom module(MacOS Sierra)

### ISSUE THREAD

**Issue by dhruv7294** [JunoLab/uber-juno#18]
Not precompiling Atom Module in my MacOS Sierra operating system.

**Comment by pfitzseb** [comment]
So, what's the error you're seeing? We can't help you without knowing what went wrong.

**Comment by dhruv7294** [comment]
So when I try to start julia in Atom. It will start to precompile Atom module. and then so many errors are thrown. 

ERROR: LoadError: MbedTLS not properly installed. Please run Pkg.build("MbedTLS")
ERROR: LoadError: Failed to precompile MbedTLS to /Users/DS/.julia/lib/v0.5/MbedTLS.ji.
ERROR: LoadError: LoadError: Failed to precompile HttpServer to /Users/DS/.julia/lib/v0.5/HttpServer.ji.
ERROR: LoadError: LoadError: Failed to precompile Mux to /Users/DS/.julia/lib/v0.5/Mux.ji.
ERROR: LoadError: Failed to precompile Blink to /Users/DS/.julia/lib/v0.5/Blink.ji.
ERROR: LoadError: Failed to precompile Atom to /Users/DS/.julia/lib/v0.5/Atom.ji.

and when i try to write Pkg.build("MbedTLS"), gives errors only.

julia> Pkg.build("MbedTLS")
INFO: Building Homebrew
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: Git must be installed and in your PATH!
Error: Git is unavailable
==============================[ ERROR: Homebrew ]===============================

LoadError: InitError: failed process: Process(`/Users/DS/.julia/v0.5/Homebrew/deps/usr/bin/brew tap --full homebrew/core`, ProcessExited(1)) [1]
during initialization of module Homebrew
while loading /Users/DS/.julia/v0.5/Homebrew/deps/build.jl, in expression starting on line 1

================================================================================
INFO: Building MbedTLS
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: Git is unavailable
Error: Failure while executing: /Users/DS/.julia/v0.5/Homebrew/deps/usr/bin/brew tap homebrew/core -q
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: Git is unavailable
Error: Failure while executing: /Users/DS/.julia/v0.5/Homebrew/deps/usr/bin/brew tap homebrew/core -q
cmake command not found. installing cmake is required for building from source.
===============================[ ERROR: MbedTLS ]===============================

LoadError: failed process: Process(`./cmake_check.sh`, ProcessExited(1)) [1]
while loading /Users/DS/.julia/v0.5/MbedTLS/deps/build.jl, in expression starting on line 74

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: MbedTLS and Homebrew had build errors.

 - packages with build errors remain installed in /Users/DS/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("MbedTLS", "Homebrew")`
 - build a single package by running its `deps/build.jl` script

================================================================================

Thank you for the help.

**Comment by MikeInnes** [comment]
It looks like `Pkg.build("Homebrew")` is failing so your best bet is to open an issue there. It may be as simple as needing to run `xcode-select --install` but don't take my word for that.

**Comment by pfitzseb** [comment]
If you're still getting this error on the newest versions of all relevant packages, please reopen.
