### ISSUE TITLE
How to reset the context after running a file

### ISSUE THREAD

**Issue by AndreiUlmeyda** [JunoLab/uber-juno#19]
Greetings,

sorry to bother you with what I understand to be an age old issue with Julia. The truth is, it haunts me every single time I try to use Julia and I have tried many hours to find actually working resolutions to it, but to no avail. So, in desperation, I turn to you. Feel free to turn me away :D 

I am in the process of becoming quite fond of Juno as my go-to Julia environment. What I am trying to do is
1. edit a file
2. run the file (for instance creating a plot in the end)
3. repeat

When exploring the language or different packages, that cycle is quite short and is repeated many times. And variable definitions persisting through reruns of the code naturally hide and exaggerate many errors and, on top of that, inhibit investigation of errors in a major way (since in order to investigate these one changes even more and even smaller things and tries to pin down what happens over even more reruns of the code).
As I understand it the current official solution to this is the function workspace(). Problem is, I cannot ever get it to work over more than one or two runs of a file.

A concrete example (in Atom/Juno):

```
using Plots
plotlyjs()

arrayWithTwoFunctions = [x->x x->2x]
map(f->plot!(f, -1, 1), arrayWithTwoFunctions)
gui()
```

The persisting object in question, here, is the plot itself. If I try to modify the plot slightly and rerun the file, for instance by changing line 4 to

`arrayWithTwoFunctions = [x->x]`

previously plotted traces are here to stay and with it previous plot layout specifications that do not return to their defaults when the code in question is deleted. And these problems are the tip of the iceberg. I tried weird constructs to maybe get the garbage collector to wipe things but what use are such hacks, even if they worked.

Now the question:
Is there a way to use the workspace function anywhere in this file (or  really any other way that is not restarting the julia kernel) to make it so the plot gets constructed from scratch and no variable from 5 runs before sits in the background and masks typos or errors in the code?

My first attempts were at the very start or end of the file lead to

```
LoadError: MethodError: Cannot `convert` an object of type Plots.PlotlyJSBackend to an object of type LastMain.Plots.AbstractBackend
This may have arisen from a call to the constructor LastMain.Plots.AbstractBackend(...),
since type constructors fall back to convert methods.
 in backend at /home/ulmeyda/.julia/v0.5/Plots/src/backends.jl:188 [inlined]
 in #plotlyjs#170(::Array{Any,1}, ::Function) at /home/ulmeyda/.julia/v0.5/Plots/src/backends.jl:20
 in plotlyjs() at /home/ulmeyda/.julia/v0.5/Plots/src/backends.jl:20
 in include_string(::Module, ::String, ::String) at /home/ulmeyda/.julia/v0.5/CodeTools/src/eval.jl:32
 in (::LastMain.Atom.##54#57{String,String})() at /home/ulmeyda/.julia/v0.5/Atom/src/eval.jl:79
 in withpath(::LastMain.Atom.##54#57{String,String}, ::String) at /home/ulmeyda/.julia/v0.5/CodeTools/src/utils.jl:30
 in withpath(::Function, ::String) at /home/ulmeyda/.julia/v0.5/Atom/src/eval.jl:45
 in macro expansion at /home/ulmeyda/.julia/v0.5/Atom/src/eval.jl:77 [inlined...
```

I could elaborate on all the ways I tried to get around the many issues but this is basically where I do not know how to proceed anymore at the moment. The only other thing I know of and did not have time to test yet is putting the code inside its own module. Would need to let the frustration cool back down to 9/10 before I try that anyway.

Help would be much appreciated.

Cheers

**Comment by AdrianSchurz** [comment]
Small update, the Plots package has some open issues concerning this. The problem for the particular package might get solved through that path, though none of the proposed solutions seem to work for me. Sigh. The issue for general variables remains in any case.

**Comment by pfitzseb** [comment]
You should be able to solve the Plots.jl issue by calling `plot()` right before your `map` command, which will create an empty plot. See [here](https://juliaplots.github.io/basics/).

The general case is only solvable by putting your code into a module and reloading that when necessary (which is exactly what `workspace` does with module `Main`) right now.

If you want to keep the changes to the usual workflow minimal, you could just define an empty module in the console (e.g. `module Scratch end`), change the editor's working module to that, eval your stuff, and do the same as workspace via redifining `Scratch` in the console (make sure that the console's working module is `Main`, not `Scratch` though!).

Otherwise have a look at the [suggested workflow](https://github.com/JunoLab/atom-julia-client/blob/master/manual/workflow.md).
