### ISSUE TITLE
Add june-dark theme?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JunoLab/uber-juno#22]
Juno in LightTable used to have this really really helpful theme, where every identifier is assigned a random but consistent colour. This would help me make the switch from LightTable to Atom.

**Comment by pfitzseb** [comment]
I don't think anyone here has plans for something like that, but feel free to try your hand at implementing something like that.

**Comment by tshort** [comment]
There's an Atom package that does this:

https://atom.io/packages/semanticolor

It seems to work with Juno, except for docstrings. 

All the colors would drive me crazy. Even the normal syntax highlighting is too colorful for my tastes. 

Suggest closing this issue.
