### ISSUE TITLE
Markup in Atom confused when using Blockquote in @doc

### ISSUE THREAD

**Issue by kellertuer** [JunoLab/uber-juno#23]
If I have the following @doc string

```
"""
    myFunction() computes something based on the reference
> My Paper I Would like to quote
> Further quote...
"""
```
The editor gets confused in its markup and does not recognize the closing `"""`. Everything until the end of the document is marked as if it was code in ` `(colorwise)

**Comment by spencerlyon2** [comment]
Thanks for reporting.

Does it work if you put a blank line between the end of the block quote and the closing `"""`?

Also, just as an FYI, this issue is more appropriate for https://github.com/JuliaEditorSupport/atom-language-julia

**Comment by kellertuer** [comment]
Indeed it does. Is that still a bug or working as intended then? Because if that is still a bug I can report it where you linked to (sorry wasn't sure which of all these Repositories is the right one for this issue).

**Comment by spencerlyon2** [comment]
No problem -- there are a lot of repositories and even I have a hard time keeping them straight sometimes!

I think it is still a bug, so reporting over there would be appreciated. Thanks!

**Comment by kellertuer** [comment]
Will do that :) But this one can hence be closed.
