### ISSUE TITLE
issues for julia 0.5

### ISSUE THREAD

**Issue by haihan** [JunoLab/uber-juno#25]
Hello,

I upgrade my julia into julia 0.5, then uber juno cannot find the path when started. It prompted the following message. Is it a way to customize the path or is there any other way to solve this issue? Thanks a lt!

> Julia could not be started.
We tried to launch Julia from:
/Applications/Julia-0.4.5.app/Contents/Resources/julia/bin/julia
This path can be changed in the settings.
Details:
  /bin/sh: /Applications/Julia-0.4.5.app/Contents/Resources/julia/bin/julia: No such file or directory

**Comment by pfitzseb** [comment]
The setting is in `Settings` > `julia-client` > `Julia Path` -- change that to point to the 0.5 binary and you should be good to go.
