### ISSUE TITLE
Nothing happened after clicking a button in tool bar

### ISSUE THREAD

**Issue by AlexLuya** [JunoLab/uber-juno#28]
Actually,after installing uber-juno,no editor got installed.So I installed this package :https://atom.io/users/JuliaEditorSupport,then I can select all code that I want to run,then click [run block ] from context menu,finally,code got run,is this supposed to be?But still,nothing happened after clicking any button in the left tool bar.

**Comment by Zueuk** [comment]
It seems that if an editor window is not focused, the "Run file" button does nothing.

**Comment by pfitzseb** [comment]
Right, but that shouldn't be much of a surprise -- who is Juno supposed to know which editor you mean? :)

**Comment by Zueuk** [comment]
Well, somehow all other IDEs seem to know how to find the currently active editor window, even if it is not focused.

**Comment by pfitzseb** [comment]
I mean I guess we could keep track of the latest focused editor, but meh... Maybe I'll get to it sometime.
