### ISSUE TITLE
Small usability issue on Windows after install

### ISSUE THREAD

**Issue by asampal** [JunoLab/uber-juno#29]
I've had this problem myself and have seen someone else report it in the Julia forum. When initially installing uber-juno, its setting, called "Disable - Don't run when Atom boots" is checked. Because of this, nothing happens after installing uber-juno, leading to some confusion. By unchecking this setting and restarting Atom, the dependent packages are then loaded. Should this setting be initially set to false? The current behavior should at least be documented in the setup readme.

**Comment by pfitzseb** [comment]
Well, in theory the installation of Juno via uber-juno should complete before restarting Atom, so at that point there's no point in installing again. Hence that setting is set to false. I suppose this might be a problem if the initial install fails for some reason.

**Comment by asampal** [comment]
Doesn't uber-juno check for all needed packages actually being there before setting that option to disabled? If it doesn't, wouldn't that change make sense?

**Comment by pfitzseb** [comment]
It does -- that option is only enabled after successfully installing all packages.
