### ISSUE TITLE
installing juno manually  

### ISSUE THREAD

**Issue by ilang6** [JunoLab/uber-juno#32]
Hi,
How can I install juno ide for atom without an internet connection.
what I mean is I can't search the atom repository and I need to install the package manually
help will be very welcomed.

**Comment by pfitzseb** [comment]
Okay, to manually install the Atom side of Juno you have to
- clone `atom-julia-client`, `atom-ink`, and `language-julia` (as the bare minimum -- you can install all other atom packages as shown below) somewhere
- open a shell in the relevant folders and 
  - call `apm install` and hope that succeeds (this will pull in all the various dependencies) as well as
  - call `apm link`

**Comment by MikeInnes** [comment]
You might find it easier to grab [JuliaPro](https://juliacomputing.com/products/juliapro.html).

**Comment by ilang6** [comment]
Thank very much for your help.
I think I just get the portable version of atom 
Install all I need on that version and bring the atom with me to my no internet place .

**Comment by ilang6** [comment]
Thank very much for your help.
I think I just get the portable version of atom 
Install all I need on that version and bring the atom with me to my no internet place .
