### ISSUE TITLE
Windows 10 64 bit installation with Julia 0.6.0 64 bit and R 3.4.1

### ISSUE THREAD

**Issue by GeoHubX** [JunoLab/uber-juno#36]
I have been using Juno since it was announced on the Julia homepage.

I frequently update my system and applications, so I have the latest versions of the Win10 OS and updates, Julia 0.6.0, and R 3.4.1, among others.

I had been running a specific analysis daily on Juno. I can run the files in that analysis in the IJulia/Jupyter interface, but prefer Juno. However, Juno is now giving me problems.

I have attached a file of the error messages I get when I try to run these same files. I have uninstalled and reinstalled Atom and Julia, after deleting all the associated files, such as .atom, .jupyter, and the various associated folders in the AppData folder, and making certain my environment variables are set correctly.

While taking time, I get the same errors, and cannot find the location of the references, so I am writing to you. Please help me if you can.

Thanks.
[Juno errors 2017-08-03.docx](https://github.com/JunoLab/uber-juno/files/1198957/Juno.errors.2017-08-03.docx)

**Comment by pfitzseb** [comment]
Not sure what is going on there, but you might be able to work around it by disabling the `Enable Powershell Wrapper` option in julia-client.

Also, please put error messages into a gist or something instead of a downloadable docx in the future.
