### ISSUE TITLE
uber-juno doesn't install other packages subsequently.

### ISSUE THREAD

**Issue by xanfus** [JunoLab/uber-juno#39]

**Comment by maxundmoritz** [comment]
I seem to have the same problem. Has there already been found a solution?
I already tried to uninstall and install it again, as well as reinstalling Atom.

**Comment by pfitzseb** [comment]
Can you go into the `uber-juno` settings and untick the `Disable` checkbox? Afterwards you can restart Atom and uber-juno should install the required packages.

**Comment by maxundmoritz** [comment]
I did reinstall Atom again and now it is working, so I did not try your solution. But thanks anyway
