### ISSUE TITLE
Error with ProfilerTree

### ISSUE THREAD

**Issue by NoelAraujo** [JunoLab/uber-juno#40]
I'm trying to run Juno.profiletree(), but there is something missing in my Atom or in my system and I can not point out what.

I've just copied the same code from the second image of Documentation page
http://docs.junolab.org/latest/man/juno_frontend.html
![modelo](https://user-images.githubusercontent.com/20143648/36460694-71375b18-16b1-11e8-8c47-b35fd1e35d30.png)

However, at Juno.profiletree() there is a message saying: "Error displaying Atom.Profiler.Tree{Atom.Profiler.Profileframe}: UndefVarError: icon not defined"
![error profiler](https://user-images.githubusercontent.com/20143648/36460661-48f0ccc0-16b1-11e8-837e-ab82ffd9e865.png)

My notebook has Fedora 27 installed and I'm using all default icons from Adwata from Gnome

Thank you for any help

**Comment by pfitzseb** [comment]
Thanks for the report! Fixed on Atom.jl master.
