### ISSUE TITLE
Juno is not insatlling in Atom ( Ubuntu) 

### ISSUE THREAD

**Issue by luk25xx** [JunoLab/uber-juno#41]
Hi, 

I am trying to install uber-Juno in Atom to for Julia in an UBUNTU device. But during installation, I get this connection error and the installation was not complete !

**Comment by pfitzseb** [comment]
What error are you getting?

**Comment by luk25xx** [comment]
@pfitzseb , The error is "There is no connection to internet or I have to send an error to ..." It appears after I started the installation process after few minutes. Later, in the Atom setting, I have the Uber-Juno module appearing as installed, but without any function and no Juno in the Packages Tab.

**Comment by pfitzseb** [comment]
You could try installing `julia-client` and `ink` manually, but this basically sounds like an issue with you internet connection/proxy settings?

**Comment by luk25xx** [comment]
@pfitzseb , I am sure my internet connection was not the issue, Proxy setting I was using the default in Ubuntu and I had no problem using any other applications or downloading packages. I tried the Julia-client as well and had the same problem, but I will try to install ink.
