### ISSUE TITLE
Add package doc feature?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JunoLab/uber-juno#43]
I just noticed the Documentation feature that allows one to search through documentation of Julia base and I love it! Would it be possible to add package doc searching too?

**Comment by pfitzseb** [comment]
You can search for package docs in the documentation pane. By default it only searches in loaded packages though. If you untick the `loaded` button the right and follow the instructions you can search in all installed packages. Be aware that regenerating the doc cache might take a *long* time.

**Comment by MikaelSlevinsky** [comment]
Cool, thanks!
