### ISSUE TITLE
atom ide feature

### ISSUE THREAD

**Issue by guslen** [JunoLab/uber-juno#46]
Hi,
I was wondering, whether there is any intention to move to atom-ide feature? wouldn’t it be feasible, since it should be helping with a lot of other stuff? Grammar detection would be one thing. Thanks for the answer!
https://ide.atom.io

**Comment by pfitzseb** [comment]
Not sure what grammar detection has anything to do with this (Atom + the lagnuage-julia) handle things just fine, but in the long term there are plans to move to a LSP based Juno, yes.
