### ISSUE TITLE
Some colors missing for Base16 Tomorrow Dark theme?

### ISSUE THREAD

**Issue by x-ji** [JunoLab/uber-juno#47]
Base16 Tomorrow Dark is one of the themes that come with Atom by default, and it is also the theme that I normally use across all editors. However, for some reason the syntax highlighting of Julia files seems to be amiss under this theme. For example, in `v::UInt32`, the `UInt32` part has the same color as `v`. This doesn't happen with the other three default themes.

**Comment by x-ji** [comment]
Sorry I'm not sure if this is an issue for this package or the package atom-language-julia. I've posted it there as well. If this is not the right place please close the issue.

**Comment by pfitzseb** [comment]
I've answered to https://github.com/JuliaEditorSupport/atom-language-julia/issues/149, so closing this.
