### ISSUE TITLE
Option to automatically insert end when starting a block?

### ISSUE THREAD

**Issue by x-ji** [JunoLab/uber-juno#48]
I know that some people might not prefer this behavior (e.g. in some Ruby packages `end` is also not inserted by default), but I personally find it nicer to already have `end` inserted just as the block itself is autocompleted. For example, when I select `function` or `if` from the autocomplete dropdown, I'd like `end` to be automatically inserted as well. Would it be possible to have such an option? Hopefully this is the right package for this issue.

**Comment by pfitzseb** [comment]
You can use the snippets built into atom-language-julia for this, e.g.:
![screenshot_20180429_113522](https://user-images.githubusercontent.com/6735977/39405216-85cbfa8c-4ba1-11e8-86e1-abad2c9de2e5.png)

Also see https://github.com/JuliaEditorSupport/atom-language-julia/issues/138 and https://github.com/JunoLab/atom-julia-client/issues/411,
