### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by MahmoudGamalEldinElewa** [JunoLab/uber-juno#49]
Whenever i'm trying to install  uber-juno i get this error

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.7.11/iojs-v1.7.11.tar.gz
gyp http 200 https://atom.io/download/electron/v1.7.11/iojs-v1.7.11.tar.gz
gyp http GET https://atom.io/download/electron/v1.7.11/SHASUMS256.txt
gyp http GET https://atom.io/download/electron/v1.7.11/win-x86/iojs.lib
gyp http GET https://atom.io/download/electron/v1.7.11/win-x64/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.7.11/SHASUMS256.txt
gyp http 200 https://atom.io/download/electron/v1.7.11/win-x86/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.7.11/win-x64/iojs.lib
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1022:11)
gyp ERR! stack     at TLSWrap.onread (net.js:569:26)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\mhdga\\AppData\\Local\\atom\\app-1.26.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\mhdga\\AppData\\Local\\atom\\app-1.26.1\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--runtime=electron" "--target=1.7.11" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd C:\Users\mhdga\.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

Compiler tools not found
Packages that depend on modules that contain C/C++ code will fail to install.
Read here for instructions on installing Python and Visual Studio.
Run apm install --check after installing to test compiling a native module.

**Comment by ptoche** [comment]
sounds like it's telling you to install Python and Visual Studio. Python is installed on MacOS, so it's a bit easier for Mac users. Looks ilke you're on Windows, so make sure you set up Python first. Check Anaconda/Miniconda, typically the recommended approach to set up Python. Go for Python 3.

**Comment by pfitzseb** [comment]
It does indeed indicate that, but you should definitely not need Python or Visual Studio to get Juno working on windows.

Can you try opening a terminal and type in `apm install julia-client`? If that goes through fine then also try `apm install ink`. If there are any errors in either command, please paste it here in its entirety.
