### ISSUE TITLE
Some syntax variants are not detected properly

### ISSUE THREAD

**Issue by fbruetting** [JunoLab/uber-juno#57]
When the cursor is at the first line of the following expression and `Shift + Enter` is pressed, an error is returned, because the instruction is aborted right after the equal sign – and thus doesn’t contain the full expression (though it’s valid Julia syntax):
```
bla =
[
    1,
    2,
]
```

Just the following works:
```
bla = [
    1,
    2,]
```

Also commented lines inside of a larger function execution leads to an error:
```
plot(a, b,
    xlab = "bla",      	#	xticks = 0:0.5:3,
)
```

**Comment by pfitzseb** [comment]
Yeah, this happens because our current code-block-finding is indentation based. So e.g.
```
plot(a, b,
    xlab = "bla",      	#	xticks = 0:0.5:3,
    )
```
does work.

**Comment by pfitzseb** [comment]
Closing in favour of https://github.com/JunoLab/CodeTools.jl/issues/9#issuecomment-396239626.
