### ISSUE TITLE
Issue instaling Uber-Juno

### ISSUE THREAD

**Issue by cp4213** [JunoLab/uber-juno#59]
Hi, i had a problem installing uber-juno package, i'm on windows and every time that i want to install the packeage, it shows me internet conection error, but i had tried with different internet conections with ethernet and still doesn't work

**Comment by Dadido3** [comment]
Probably the same issue here, i get this error while installing Uber-Juno:

![grafik](https://user-images.githubusercontent.com/6549004/43224841-cd9e4f0e-9057-11e8-886b-af538df24ec2.png)
