### ISSUE TITLE
Stuck Path Message

### ISSUE THREAD

**Issue by ChrisRackauckas** [JunoLab/uber-juno#6]
Every once in awhile on Windows 10 the path message gets stuck on the screen and the only way to get rid of it is to close Atom. See the image below.

![stuckmessages](https://cloud.githubusercontent.com/assets/1814174/15653963/2f165bca-2645-11e6-9659-ad53af97b985.PNG)

**Comment by pfitzseb** [comment]
This might've been fixed by https://github.com/JunoLab/atom-julia-client/commit/73b76cd1bf1e07a727d4767a369566a0895c1c8a. Please reopen if you see this again.
