### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by ayouman** [JunoLab/uber-juno#60]
Hi, 

Having installed and reinstalled,... and reinstalled, both atom and uber-juno, on fedora 28,
I keep getting the following error message when I attempt to run Julia on "hello world":

Starting Julia...
ERROR: LoadError: ArgumentError: Module Atom not found in current path.
Run `Pkg.add("Atom")` to install the Atom package.
while loading /home/simon/.atom/packages/julia-client/script/boot_repl.jl, in expression starting on line 21

After searching the web I found a similar problem dating back several years:
https://stackoverflow.com/questions/39419502/cannot-start-julia-in-atom-loaderror-argumenterror-juno-not-found-in-path

I would be very grateful for any advice

Thanks 
 
Julia has exited. Press Enter to start a new session.

**Comment by pfitzseb** [comment]
Can you try again with update packages (both julia-client and ink)? That issue should be fixed by now.
