### ISSUE TITLE
High CPU and memory use

### ISSUE THREAD

**Issue by sericson0** [JunoLab/uber-juno#61]
I am trying to run Julia from Atom using the Juno package. When I run Julia or Atom alone (without the Juno package added) I have no problems. However, once I install the Juno package and try and run Julia from Atom i get a spike in cpu and memory use. I have attached an example of the cpu and memory usage without any programs running (when I just open Atom) 
I am using an i7 - 5600U @ 2.60GHz and 8GB of ram running Windows 10 if it helps

![task manager picture](https://user-images.githubusercontent.com/24363768/43939068-939ae88e-9c24-11e8-9542-cad5787470bb.PNG)

**Comment by justinpriest** [comment]
I have the same issue with similar memory usage by Atom + Juno.

**Comment by pfitzseb** [comment]
What projects do you have open (in the project list on the left)? If there are any very big directories there than Atom will usually take quite some time to index them and look for git modules etc. 

> However, once I install the Juno package and try and run Julia from Atom i get a spike in cpu and memory use.

If it's only a spike than that's to be expected -- we spin up a couple of Julia processes for you, which initially takes a lot of CPU power and RAM. You might want to switching from `Boot Mode: Cycler` to `Boot Mode: Basic` and see if that changes things.

**Comment by sericson0** [comment]
Changing the Boot Mode seems to have helped. Thank you!
