### ISSUE TITLE
Can't install the package

### ISSUE THREAD

**Issue by Glaum96** [JunoLab/uber-juno#62]
I got this message:

Juno: Error installing package julia-client

Please check your internet connection, or report this to
http://discuss.junolab.org
and we'll try to help.
–––
Error: Installing “julia-client@0.7.3” failed.

**Comment by pfitzseb** [comment]
What happens if you open a terminal somewhere and type in `apm install julia-client`?

**Comment by Glaum96** [comment]
I get lots of error messages.

Med Vennlig Hilsen
Haakon Gunleiksrud
+47 954 07 576


Den tir. 21. aug. 2018 kl. 12:50 skrev Sebastian Pfitzner <
notifications@github.com>:

**Comment by pfitzseb** [comment]
Would you mind pasting them here or in a gist?

**Comment by Glaum96** [comment]
C:\Users\haako>apm install julia-client
Installing julia-client to C:\Users\haako\.atom\packages failed

> node-pty-prebuilt@0.7.6 install
C:\Users\haako\AppData\Local\Temp\apm-install-dir-118721-11696-1xvx75r.8g667s0pb9\node_modules\julia-client\node_modules\node-pty-prebuilt
> prebuild-install || node scripts/install.js


C:\Users\haako\AppData\Local\Temp\apm-install-dir-118721-11696-1xvx75r.8g667s0pb9\node_modules\julia-client\node_modules\node-pty-prebuilt>if
not defined npm_config_node_gyp (node
"C:\Users\haako\AppData\Local\atom\app-1.29.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js"
rebuild --build_v8_with_gn=false )  else (node
"C:\Users\haako\AppData\Local\atom\app-1.29.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js"
rebuild --build_v8_with_gn=false )
C:\Users\haako\AppData\Local\Temp\apm-install-dir-118721-11696-1xvx75r.8g667s0pb9
`-- (empty)


npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to
"coffeescript" (no hyphen)
prebuild-install WARN install unexpected end of file
gyp ERR! configure error
gyp ERR! stack Error: Python executable
"C:\Users\haako\Miniconda3\python.EXE" is v3.5.2, which is not supported by
gyp.
gyp ERR! stack You can pass the --python switch to point to Python >=
v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion
(C:\Users\haako\AppData\Local\atom\app-1.29.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at
C:\Users\haako\AppData\Local\atom\app-1.29.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command
"C:\\Users\\haako\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\bin\\node.exe"
"C:\\Users\\haako\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd
C:\Users\haako\AppData\Local\Temp\apm-install-dir-118721-11696-1xvx75r.8g667s0pb9\node_modules\julia-client\node_modules\node-pty-prebuilt
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open
'C:\Users\haako\AppData\Local\Temp\apm-install-dir-118721-11696-1xvx75r.8g667s0pb9\package.json'
npm WARN apm-install-dir-118721-11696-1xvx75r.8g667s0pb9 No description
npm WARN apm-install-dir-118721-11696-1xvx75r.8g667s0pb9 No repository
field.
npm WARN apm-install-dir-118721-11696-1xvx75r.8g667s0pb9 No README data
npm WARN apm-install-dir-118721-11696-1xvx75r.8g667s0pb9 No license field.
npm ERR! Windows_NT 10.0.17134
npm ERR! argv
"C:\\Users\\haako\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\bin\\node.exe"
"C:\\Users\\haako\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js"
"--globalconfig" "C:\\Users\\haako\\.atom\\.apm\\.apmrc" "--userconfig"
"C:\\Users\\haako\\.atom\\.apmrc" "install"
"C:\\Users\\haako\\AppData\\Local\\Temp\\d-118721-11696-l8ydul.darvu6jemi\\package.tgz"
"--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node
scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script
'prebuild-install || node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the
node-pty-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node scripts/install.js
npm ERR! You can get information on how to open an issue for this project
with:
npm ERR!     npm bugs node-pty-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-pty-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
 C:\Users\haako\AppData\Local\Temp\apm-install-dir-118721-11696-1xvx75r.8g667s0pb9\npm-debug.log
npm ERR! code 1


C:\Users\haako>
Med Vennlig Hilsen
Haakon Gunleiksrud
+47 954 07 576


Den tir. 21. aug. 2018 kl. 12:56 skrev Sebastian Pfitzner <
notifications@github.com>:

**Comment by pfitzseb** [comment]
This seems like a problem with either your internet connection (unlikely) or your anti virus solution -- try disabling the latter for the duration of the Juno installation.
