### ISSUE TITLE
Julia not under packages menu after update to Atom 1.30.0

### ISSUE THREAD

**Issue by ssuds** [JunoLab/uber-juno#64]
uber-juno, julia-client, and ink packages are all installed.

Juno and Julia were working fine prior to this latest update.

**Comment by ssuds** [comment]
![image](https://user-images.githubusercontent.com/10721344/45469817-f8077280-b6df-11e8-824e-43fd6fc86925.png)

**Comment by pfitzseb** [comment]
Hm, I think the update failed for you. Please try the following:

1. Close all Atom instances.
2. Open a terminal.
3. Call `apm uninstall julia-client`, followed by `apm install julia-client`.

**Comment by ssuds** [comment]
@pfitzseb that did the trick, thank you!
