### ISSUE TITLE
I can not install the uber-juno package

### ISSUE THREAD

**Issue by razambuja** [JunoLab/uber-juno#68]
I can not install the uber-juno package.

Error:
"Please check your internet connection, or report this to
    http://discuss.junolab.org
and we'll try to help.
    –––
Error: Installing “julia-client@0.7.10” failed."

I'm connected.

What should I do?

**Comment by gyuholim** [comment]
I had exactly the same error message as yours.
Atom 1.39.1 did not work for me but Atom 1.38.* works for me. 
My computer is  Windows 10 [Korean version] as OS and LG notebook.
Seoul Korea.
