### ISSUE TITLE
Incorrect indentation

### ISSUE THREAD

**Issue by ikzk** [JunoLab/uber-juno#7]
Juno indents my code as
![ss](https://cloud.githubusercontent.com/assets/18649508/15871792/5ffe2eb8-2cc4-11e6-87af-27a9d5e3770c.png)
while it should be
![ss](https://cloud.githubusercontent.com/assets/18649508/15871812/752862f4-2cc4-11e6-86fc-e27bb18fa4ae.png)

**Comment by MikeInnes** [comment]
I opened an issue for this over at the language plugin: https://github.com/JuliaLang/atom-language-julia/issues/71
