### ISSUE TITLE
 Installing “ink@0.9.13” failed.

### ISSUE THREAD

**Issue by HerAdri** [JunoLab/uber-juno#70]
when installing uber-Juno I receive the following alerata:
Please check your internet connection, or report this to
    http://discuss.junolab.org
and we'll try to help.
    –––
Error: Installing “ink@0.9.13” failed.
but installs without problems:
language-julia
uber-juno
and the installation stops without concluding it

**Comment by pfitzseb** [comment]
Can you try running `apm install ink` in a terminal and paste the output here if it still fails?

**Comment by HerAdri** [comment]
Microsoft Windows [Version 10.0.17134.472]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\user>apm install ink
Installing ink to C:\Users\user\.atom\packages failed

> ink@0.9.13 postinstall C:\Users\user\AppData\Local\Temp\apm-install-dir-1181130-6236-1dzy4rn.fbtr\node_modules\ink
> node scripts/postinstall.js


npm WARN lifecycle npm is using C:\Users\user\AppData\Local\atom\app-1.33.1\resources\app\apm\bin\node.exe but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
'node' is not recognized as an internal or external command,
operable program or batch file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\user\AppData\Local\Temp\apm-install-dir-1181130-6236-1dzy4rn.fbtr\package.json'
npm WARN apm-install-dir-1181130-6236-1dzy4rn.fbtr No description
npm WARN apm-install-dir-1181130-6236-1dzy4rn.fbtr No repository field.
npm WARN apm-install-dir-1181130-6236-1dzy4rn.fbtr No README data
npm WARN apm-install-dir-1181130-6236-1dzy4rn.fbtr No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ink@0.9.13 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ink@0.9.13 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\.atom\.apm\_logs\2018-12-30T10_05_11_824Z-debug.log


C:\Users\user>

**Comment by HerAdri** [comment]
[2018-12-30T10_05_11_824Z-debug.log](https://github.com/JunoLab/uber-juno/files/2717051/2018-12-30T10_05_11_824Z-debug.log)
