### ISSUE TITLE
Can't type underscore in the REPL

### ISSUE THREAD

**Issue by stla** [JunoLab/uber-juno#74]
Hello,

 When I type an underscore in the REPL of uber-juno, I get a white space instead.

**Comment by pfitzseb** [comment]
That's a known upstream issue with a couple of fonts (most notably Deja Vu Mono), so for now you'll need to use a different font in Atom.

**Comment by stla** [comment]
Thank you. I set the **monospace** font in *Julia -> Settings -> Editor* and this works fine.
